---
- name: Resolve old switch fabric absence
  ansible.builtin.include_role:
    name: fabric_devices_info
    apply:
      tags:
        - switch_refresh_cleanup_old
  vars:
    fabric_devices_info_state: gathered
    fabric_devices_info_config_verify: false
    fabric_devices_info_config:
      - fabric_devices:
          - fabric_site_hierarchy: "{{ refresh_item.fabric_site_name_hierarchy }}"
            device_identifier:
              - ip_address: "{{ switch_refresh_old_fabric_expected_ips }}"
            timeout: >-
              {{
                refresh_item.fabric_validation_timeout |
                default(switch_refresh_fabric_validation_timeout)
              }}
            retries: >-
              {{
                refresh_item.fabric_validation_retries |
                default(switch_refresh_fabric_validation_retries)
              }}
            interval: >-
              {{
                refresh_item.fabric_validation_interval |
                default(switch_refresh_fabric_validation_interval)
              }}
            requested_info:
              - fabric_info

- name: Validate old switch fabric absence
  ansible.builtin.include_tasks: validate_cleanup_batch_fabric_absence.yml
