FROM quay.io/centos/centos:stream9

RUN dnf install -y python3.12 python3.12-pip git gcc python3.12-devel && \
    alternatives --install /usr/bin/python python /usr/bin/python3.12 1 && \
    pip3.12 install --upgrade pip

RUN pip install git+https://github.com/ansible/ansible@devel

RUN mkdir -p /root/ansible_collections

WORKDIR /root/ansible_collections
