---
# tasks file for sda_host_port_migration_config_generator
- name: Generate SDA host port migration playbook configuration
  cisco.catalystcenter.sda_host_port_migration_playbook_config_generator:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    catalystcenter_log_append: "{{ catalystcenter_log_append | default(false) }}"
    catalystcenter_log_file_path: "{{ catalystcenter_log_file_path | default('catalystcenter.log') }}"
    state: "{{ sda_host_port_migration_config_generator_state }}"
    file_path: "{{ sda_host_port_migration_config_generator_file_path if sda_host_port_migration_config_generator_file_path is not none else omit }}"
    file_mode: "{{ sda_host_port_migration_config_generator_file_mode }}"
    config: "{{ sda_host_port_migration_config_generator_config if sda_host_port_migration_config_generator_config is not none else omit }}"
  register: sda_host_port_migration_config_generator_result

- name: Display SDA host port migration generator result
  ansible.builtin.debug:
    var: sda_host_port_migration_config_generator_result
  when: catalystcenter_debug | default(false)
