---
- name: Global Credentials
  hosts: catalystcenter_servers
  vars_files:
    - vars/credentials.yml
  gather_facts: false
  tasks:
    - name: Create CLI Credential
      cisco.catalystcenter.cli_credential:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        state: present
        validate_response_schema: false
        enablePassword: C2sco456!
        username: Test2
        password: C2sco456!2
        description: Test2 Ansible

    - name: Create SNMPV3 Credential
      cisco.catalystcenter.snmpv3_credential:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        state: present
        validate_response_schema: false
        username: user2
        snmpMode: NOAUTHNOPRIV
        description: user2 222
