---
- name: Reserve ip subpool
  hosts: catalystcenter_servers
  vars_files:
    - vars/credentials.yml
  gather_facts: false
  vars:
    site: 4b9ece30-ef82-4141-ab37-62b33286195b

  tasks:
    - name: Create reservation
      cisco.catalystcenter.reserve_ip_subpool:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        state: present
        ignoreInheritedGroups: true
        name: SubPool-Sucursal-01
        type: Generic
        ipv6AddressSpace: false
        ipv4GlobalPool: 10.10.0.0/16
        ipv4Prefix: true
        ipv4PrefixLength: 28
        ipv4Subnet: 10.10.1.0
        ipv4GateWay: 10.10.1.1
        ipv4DhcpServers:
          - 10.10.1.2
        ipv4DnsServers:
          - 8.8.8.8
          - 8.8.4.4
        slaacSupport: false
        siteId: "{{ site }}"

    - name: Get Reservations
      cisco.catalystcenter.reserve_ip_subpool_info:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        siteId: "{{ site }}"
      register: ip_pool

    - name: Print Reservations
      ansible.builtin.debug:
        var: ip_pool
