#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: compliance_policys
short_description: Resource module for Compliance Policys
description:
  - Manage operations create, update and delete of the resource Compliance Policys.
  - This API operation creates a new compliance policy.
  - Deletes a specific compliance policy.
  - Updates the details of an existing compliance policy.
version_added: '2.3.0'
extends_documentation_fragment:
  - cisco.catalystcenter.module
author: Bryan Vargas (@bvargasre)
options:
  description:
    description: An optional field for providing a detailed description of the compliance policy.
    type: str
  id:
    description: The `id` of the compliance policy.
    type: str
  name:
    description: The unique name of the compliance policy.
    type: str
  rulesCount:
    description: The total number of rules within the compliance policy.
    type: int
  sitesCount:
    description: The total count of site IDs to which the compliance policy applies.
    type: int
  source:
    description: The source of the compliance policy. Source can be - `USER` Indicates the policy was created by the user.
      - `SYSTEM` Indicates the policy was automatically generated by the system.
    type: str
  status:
    description: The status of the compliance policy. Status can be - `ACTIVE` The policy is fully configured and operational.
      - `NO_RULES_CONFIGURED` The policy lacks defined rules. - `NO_CONDITIONS_CONFIGURED` The policy lacks conditions in
      all its rules. - `NO_SITES_ASSIGNED` The policy is not assigned to any sites. - `SITE_VARIABLES_PENDING` Awaiting resolution
      of site-specific variables.
    type: str
requirements:
  - catalystcentersdk >= 3.1.6.0.2
  - python >= 3.12
seealso:
  - name: Cisco Catalyst Center documentation for Compliance CreateANewPolicy
    description: Complete reference of the CreateANewPolicy API.
    link: https://developer.cisco.com/docs/dna-center/#!create-a-new-policy
  - name: Cisco Catalyst Center documentation for Compliance DeleteASpecificPolicy
    description: Complete reference of the DeleteASpecificPolicy API.
    link: https://developer.cisco.com/docs/dna-center/#!delete-a-specific-policy
  - name: Cisco Catalyst Center documentation for Compliance UpdateAnExistingPolicy
    description: Complete reference of the UpdateAnExistingPolicy API.
    link: https://developer.cisco.com/docs/dna-center/#!update-an-existing-policy
notes:
  - SDK Method used are
    compliance.Compliance.create_a_new_policy,
    compliance.Compliance.delete_a_specific_policy,
    compliance.Compliance.update_an_existing_policy,
  - Paths used are
    post /dna/intent/api/v1/compliancePolicys,
    delete /dna/intent/api/v1/compliancePolicys/{id},
    put /dna/intent/api/v1/compliancePolicys/{id},
"""

EXAMPLES = r"""
---
- name: Create
  cisco.catalystcenter.compliance_policys:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: present
    description: string
    id: string
    name: string
    rulesCount: 0
    sitesCount: 0
    source: string
    status: string
- name: Delete by id
  cisco.catalystcenter.compliance_policys:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: absent
    id: c9eef5e2-1eab-426c-be77-97ee81dcba05
- name: Update by id
  cisco.catalystcenter.compliance_policys:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: present
    description: string
    id: string
    name: string
    rulesCount: 0
    sitesCount: 0
    source: string
    status: string
"""
RETURN = r"""
catalystcenter_response:
  description: A dictionary or list with the response returned by the Cisco Catalyst Center Python SDK
  returned: always
  type: dict
  sample: >
    {
      "response": {
        "taskId": "string",
        "url": "string"
      },
      "version": "string"
    }
"""
