#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: iot_fabric_prp_configuration_models_delete_create
short_description: Resource module for Iot Fabric Prp Configuration Models Delete Create
description:
  - Manage operation create of the resource Iot Fabric Prp Configuration Models Delete Create. - > This API creates a configuration
    model required to delete existing PRP configuration from the device. This is a pre-requisite if you want to preview the
    generated config for the provisioning intent.
version_added: '2.11.0'
extends_documentation_fragment:
  - cisco.catalystcenter.module
author: Bryan Vargas (@bvargasre)
options:
  activityDescription:
    description: ActivityDescription query parameter. Optional free-form description that is recorded in the audit log for
      this activity. If omitted, a default description is generated by the server based on the target device.
    type: str
  interfaceName:
    description: Name of the interface. It can be identified in the response of API - `/dna/intent/api/v1/iot/fabric/prp/query`.
      The corresponding LAN-A or LAN-B interface name can be retrieved from the `prpLanDevicesInfo` object in the response.
    type: str
  networkDeviceId:
    description: Identifier of the network device. It is the `id` attribute in the response of API - `/dna/intent/api/v1/networkDevices`.
      It must be networkDeviceId of the LAN-A / LAN-B device.
    type: str
requirements:
  - catalystcentersdk >= 3.1.6.0.2
  - python >= 3.12
seealso:
  - name: Cisco Catalyst Center documentation for Industrial Configuration CreateConfigurationModelForDeletingPRPConfiguration
    description: Complete reference of the CreateConfigurationModelForDeletingPRPConfiguration API.
    link: https://developer.cisco.com/docs/dna-center/#!create-configuration-model-for-deleting-prp-configuration
notes:
  - SDK Method used are
    industrial_configuration.IndustrialConfiguration.create_configuration_model_for_deleting_prp_configuration,
  - Paths used are
    post /dna/intent/api/v1/iot/fabric/prp/configurationModels/delete,
"""

EXAMPLES = r"""
---
- name: Create
  cisco.catalystcenter.iot_fabric_prp_configuration_models_delete_create:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    activityDescription: PRP configuration deploy for device IE3400-Edge-01
    interfaceName: string
    networkDeviceId: string
"""
RETURN = r"""
catalystcenter_response:
  description: A dictionary or list with the response returned by the Cisco Catalyst Center Python SDK
  returned: always
  type: dict
  sample: >
    {
      "response": {
        "taskId": "string",
        "url": "string"
      },
      "version": "string"
    }
"""
