#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: iot_fabric_prp_configuration_models_create
short_description: Resource module for Iot Fabric Prp Configuration Models Create
description:
  - Manage operation create of the resource Iot Fabric Prp Configuration Models Create. - > This API creates a configuration
    model needed for performing PRP creation. This is a pre-requisite if you want to preview the generated config for the
    provisioning intent.
version_added: '2.11.0'
extends_documentation_fragment:
  - cisco.catalystcenter.module
author: Bryan Vargas (@bvargasre)
options:
  activityDescription:
    description: ActivityDescription query parameter. Optional free-form description that is recorded in the audit log for
      this activity. If omitted, a default description is generated by the server based on the target device.
    type: str
  allowedVlans:
    description: VLANs that are permitted on the PRP channel.
    type: str
  channelNumber:
    description: Identifies a channel group that aggregates two physical interfaces for redundancy. Value can be either 1
      or 2.
    type: int
  description:
    description: Information about the PRP request.
    type: str
  interfaceNames:
    description: List of interface names. Must contain exactly 2 interfaces.
    elements: str
    type: list
  isPtpEnabled:
    description: Indicates whether PTP alarms are enabled.
    type: bool
  isStpBpduFilter:
    description: Indicates whether BPDU filtering is enabled on the port-channel interface.
    type: bool
  isStpPortfastTrunk:
    description: Indicates whether PortFast is enabled on the interface in trunk mode.
    type: bool
  lanBDeviceDetails:
    description: LAN-B Device Information.
    suboptions:
      interfaceName:
        description: Name of the interface.
        type: str
      networkDeviceId:
        description: Identifier of the network device. It is the `id` attribute in the response of API - `/dna/intent/api/v1/networkDevices`.
        type: str
    type: dict
  networkDeviceId:
    description: Identifier of the network device. It is the `id` attribute in the response of API - `/dna/intent/api/v1/networkDevices`.
      It must be networkDeviceId of the Redbox device.
    type: str
  supervisionFrameOption:
    description: PRP supervision frame option.
    suboptions:
      isVlanAwareEnabled:
        description: Indicates whether VLAN Aware mode is enabled.
        type: bool
      isVlanAwareRejectUntagged:
        description: Indicates whether untagged supervision frames are rejected.
        type: bool
      isVlanTagged:
        description: Indicates whether VLAN tagging is enabled.
        type: bool
      vlanAwareAllowedVlans:
        description: Allowed VLANs in VLAN Aware Mode.
        type: str
      vlanId:
        description: Identifier for a VLAN.
        type: int
    type: dict
  switchPortMode:
    description: Trunking mode of the interface.
    type: str
requirements:
  - catalystcentersdk >= 3.1.6.0.2
  - python >= 3.12
seealso:
  - name: Cisco Catalyst Center documentation for Industrial Configuration CreateConfigurationModelForAddingPRPConfiguration
    description: Complete reference of the CreateConfigurationModelForAddingPRPConfiguration API.
    link: https://developer.cisco.com/docs/dna-center/#!create-configuration-model-for-adding-prp-configuration
notes:
  - SDK Method used are
    industrial_configuration.IndustrialConfiguration.create_configuration_model_for_adding_prp_configuration,
  - Paths used are
    post /dna/intent/api/v1/iot/fabric/prp/configurationModels/create,
"""

EXAMPLES = r"""
---
- name: Create
  cisco.catalystcenter.iot_fabric_prp_configuration_models_create:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    activityDescription: PRP configuration deploy for device IE3400-Edge-01
    allowedVlans: string
    channelNumber: 0
    description: string
    interfaceNames:
      - string
    isPtpEnabled: true
    isStpBpduFilter: true
    isStpPortfastTrunk: true
    lanBDeviceDetails:
      interfaceName: string
      networkDeviceId: string
    networkDeviceId: string
    supervisionFrameOption:
      isVlanAwareEnabled: true
      isVlanAwareRejectUntagged: true
      isVlanTagged: true
      vlanAwareAllowedVlans: string
      vlanId: 0
    switchPortMode: string
"""
RETURN = r"""
catalystcenter_response:
  description: A dictionary or list with the response returned by the Cisco Catalyst Center Python SDK
  returned: always
  type: dict
  sample: >
    {
      "response": {
        "taskId": "string",
        "url": "string"
      },
      "version": "string"
    }
"""
