#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: iot_fabric_prp_deploy_delete
short_description: Resource module for Iot Fabric Prp Deploy Delete
description:
  - Manage operation delete of the resource Iot Fabric Prp Deploy Delete.
  - This API deletes the PRP configuration without generating a config preview.
version_added: '2.11.0'
extends_documentation_fragment:
  - cisco.catalystcenter.module
author: Bryan Vargas (@bvargasre)
options:
  activityDescription:
    description: ActivityDescription query parameter. Optional free-form description that is recorded in the audit log for
      this activity. If omitted, a default description is generated by the server based on the target device.
    type: str
  interfaceName:
    description: InterfaceName query parameter. Name of the interface. It can be identified in the response of API - `/dna/intent/api/v1/iot/fabric/prp/query`.
      The corresponding LAN-A or LAN-B interface name can be retrieved from the `prpLanDevicesInfo` object in the response.
    type: str
  networkDeviceId:
    description: NetworkDeviceId query parameter. Identifier of the network device. It is the `id` attribute in the response
      of API - `/dna/intent/api/v1/networkDevices`.
    type: str
requirements:
  - catalystcentersdk >= 3.2.3.0.0
  - python >= 3.12
seealso:
  - name: Cisco Catalyst Center documentation for Industrial Configuration DeletePRPConfigurationWithoutGeneratingAConfigPreview
    description: Complete reference of the DeletePRPConfigurationWithoutGeneratingAConfigPreview API.
    link: https://developer.cisco.com/docs/dna-center/#!delete-prp-configuration-without-generating-a-config-preview
notes:
  - SDK Method used are
    industrial_configuration.IndustrialConfiguration.delete_prp_configuration_without_generating_a_config_preview,
  - Paths used are
    delete /dna/intent/api/v1/iot/fabric/prp/deploy,
"""

EXAMPLES = r"""
---
- name: Delete all
  cisco.catalystcenter.iot_fabric_prp_deploy_delete:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    activityDescription: PRP configuration deploy for device IE3400-Edge-01
    interfaceName: Gig1/1
    networkDeviceId: dd584a8a-a7ae-4323-97f4-ab950cab52a6
"""
RETURN = r"""
catalystcenter_response:
  description: A dictionary or list with the response returned by the Cisco Catalyst Center Python SDK
  returned: always
  type: dict
  sample: >
    {
      "response": {
        "taskId": "string",
        "url": "string"
      },
      "version": "string"
    }
"""
