#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: wireless_settings_pre_auth_acls_info
short_description: Information module for Wireless Settings Pre Auth Acls
description:
  - Get all Wireless Settings Pre Auth Acls.
  - Get Wireless Settings Pre Auth Acls by id. - > This API allows users to retrieve information about a specific Pre-Auth
    ACL by ID. This API allows users to retrieve information about a specific Pre-Auth ACL by ID. - > This API allows users
    to retrieve information about all Pre-Auth ACLs in the system. This API allows users to retrieve information about all
    Pre-Auth ACLs in the system.
version_added: '2.11.0'
extends_documentation_fragment:
  - cisco.catalystcenter.module_info
author: Bryan Vargas (@bvargasre)
options:
  headers:
    description: Additional headers.
    type: dict
  id:
    description:
      - Id path parameter. Pre-Auth ACL ID.
    type: str
  limit:
    description:
      - Limit query parameter.
    type: int
  offset:
    description:
      - Offset query parameter.
    type: int
  aclListName:
    description:
      - AclListName query parameter. Pre-Auth ACL List Name.
    type: str
requirements:
  - catalystcentersdk >= 3.1.6.0.2
  - python >= 3.12
seealso:
  - name: Cisco Catalyst Center documentation for Wireless GetAllPreAuthACLs
    description: Complete reference of the GetAllPreAuthACLs API.
    link: https://developer.cisco.com/docs/dna-center/#!get-all-pre-auth-ac-ls
  - name: Cisco Catalyst Center documentation for Wireless GetPreAuthACLByID
    description: Complete reference of the GetPreAuthACLByID API.
    link: https://developer.cisco.com/docs/dna-center/#!get-pre-auth-acl-by-id
notes:
  - SDK Method used are
    wireless.Wireless.get_all_pre_auth_acls,
    wireless.Wireless.get_pre_auth_acl_by_id,
  - Paths used are
    get /dna/intent/api/v1/wirelessSettings/preAuthAcls,
    get /dna/intent/api/v1/wirelessSettings/preAuthAcls/{id},
"""

EXAMPLES = r"""
---
- name: Get all Wireless Settings Pre Auth Acls
  cisco.catalystcenter.wireless_settings_pre_auth_acls_info:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    headers: "{{my_headers | from_json}}"
    limit: 500
    offset: 1
    aclListName: string
  register: result
- name: Get Wireless Settings Pre Auth Acls by id
  cisco.catalystcenter.wireless_settings_pre_auth_acls_info:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    headers: "{{my_headers | from_json}}"
    id: string
  register: result
"""
RETURN = r"""
catalystcenter_response:
  description: A dictionary or list with the response returned by the Cisco Catalyst Center Python SDK
  returned: always
  type: dict
  sample: >
    {
      "response": {
        "id": "string",
        "aclListName": "string",
        "aclName": "string",
        "ipv6AclEnabled": true,
        "includeAutoGeneratedRules": true,
        "ipAclRules": [
          {
            "sourceAddress": {},
            "sourceSubnetMaskOrPrefix": 0,
            "destinationAddress": {},
            "destinationSubnetMaskOrPrefix": 0,
            "sourcePorts": "string",
            "destinationPorts": "string",
            "protocol": {}
          }
        ],
        "walledGardenUrls": [
          "string"
        ]
      },
      "version": "string"
    }
"""
