#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: wireless_profiles
short_description: Resource module for Wireless Profiles
description:
  - Manage operations create, update and delete of the resource Wireless Profiles.
  - This API allows the user to create a Wireless Network Profile.
  - This API allows the user to delete Wireless Network Profile by Id. - > This API allows the user to update a Wireless Network
    Profile by Id.Note that, when performing a PUT operation on a wireless network profile, it is essential to provide a complete
    payload. This is because the wireless network profile is tightly integrated with other network design entities. Consequently,
    all fields must be included—not just the fields to be updated. Any missing fields will be set to their default or null
    values. To ensure all fields are accurately populated, consider using the GET operation to retrieve the current resource
    data before proceeding with the PUT operation.
version_added: '1.0.0'
extends_documentation_fragment:
  - cisco.catalystcenter.module
author: Bryan Vargas (@bvargasre)
options:
  additionalInterfaces:
    description: These interfaces will be configured on the device as independent interfaces in addition to the interfaces
      mapped to SSIDs.
    elements: str
    type: list
  apZones:
    description: List of apZones Attached to wireless Profile.
    elements: dict
    suboptions:
      apZoneName:
        description: Name of the apZone.
        type: str
      rfProfileName:
        description: Name of the RF profile attached to the AP Zone.
        type: str
      ssids:
        description: Wireless Profiles's ssids.
        elements: str
        type: list
    type: list
  featureTemplates:
    description: Feature Templates which needs to be associated to the wireless network profile.
    elements: dict
    suboptions:
      id:
        description: Feature Template UUID.
        type: str
      ssids:
        description: Wireless Profiles's ssids.
        elements: str
        type: list
    type: list
  id:
    description: Id.
    type: str
  ssidDetails:
    description: SSID Details.
    elements: dict
    suboptions:
      anchorGroupName:
        description: Anchor Group Name. Below are points to consider - If 'enableFabric' field is set to true,'anchorGroupName'
          must be null.If 'anchorGroupName' is null,'enableFabric' must be false. - If 'interfaceName' field is non-null,'anchorGroupName'
          must be null.If 'anchorGroupName' is non-null,'interfaceName' must be null.
        type: str
      dot11beProfileId:
        description: 802.11be Profile Id. Applicable to IOS controllers with version 17.15.2 and higher.
        type: str
      enableFabric:
        description: True if fabric is enabled, else false. Flex and fabric cannot be enabled simultaneously and a profile
          can only contain either flex SSIDs or fabric SSIDs and not both at the same time.
        type: bool
      flexConnect:
        description: FlexConnect.
        suboptions:
          enableFlexConnect:
            description: True if flex connect is enabled, else false. Flex and fabric cannot be enabled simultaneously and
              a profile can only contain either flex SSIDs or fabric SSIDs and not both at the same time.
            type: bool
          localToVlan:
            description: Local to VLAN ID.
            type: int
        type: dict
      interfaceName:
        description: Interface Name. Default Value management.
        type: str
      policyProfileName:
        description: "Policy Profile Name. If 'policyProfileName' is not provided, the value of 'wlanProfileName' will be
          assigned to it. If 'profileName' is also not provided, an autogenerated name will be used. Autogenerated name is
          generated by appending 'ssidName' field's value with '_profile' (Example If 'ssidName' = 'ExampleSsid', then autogenerated
          name will be 'ExampleSsid_profile')."
        type: str
      ssidName:
        description: SSID Name.
        type: str
      vlanGroupName:
        description: VLAN Group Name.Below are points to consider - If 'interfaceName' is non-null in payload,'vlanGroupName'
          must be null.If 'vlanGroupName' is non-null,'interfaceName' must be null.
        type: str
      wlanProfileName:
        description: WLAN Profile Name.
        type: str
    type: list
  wirelessProfileName:
    description: Wireless Profile Name.
    type: str
requirements:
  - catalystcentersdk >= 3.1.6.0.2
  - python >= 3.12
seealso:
  - name: Cisco Catalyst Center documentation for Wireless CreateWirelessProfile
    description: Complete reference of the CreateWirelessProfile API.
    link: https://developer.cisco.com/docs/dna-center/#!create-wireless-profile
  - name: Cisco Catalyst Center documentation for Wireless DeleteWirelessProfile
    description: Complete reference of the DeleteWirelessProfile API.
    link: https://developer.cisco.com/docs/dna-center/#!delete-wireless-profile
  - name: Cisco Catalyst Center documentation for Wireless UpdateWirelessProfile
    description: Complete reference of the UpdateWirelessProfile API.
    link: https://developer.cisco.com/docs/dna-center/#!update-wireless-profile
notes:
  - SDK Method used are
    wireless.Wireless.create_wireless_profile,
    wireless.Wireless.delete_wireless_profile,
    wireless.Wireless.update_wireless_profile,
  - Paths used are
    post /dna/intent/api/v1/wirelessProfiles,
    delete /dna/intent/api/v1/wirelessProfiles/{id},
    put /dna/intent/api/v1/wirelessProfiles/{id},
"""

EXAMPLES = r"""
---
- name: Update by id
  cisco.catalystcenter.wireless_profiles:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: present
    additionalInterfaces:
      - string
    apZones:
      - apZoneName: string
        rfProfileName: string
        ssids:
          - string
    featureTemplates:
      - id: string
        ssids:
          - string
    id: string
    ssidDetails:
      - anchorGroupName: string
        dot11beProfileId: string
        enableFabric: true
        flexConnect:
          enableFlexConnect: true
          localToVlan: 0
        interfaceName: string
        policyProfileName: string
        ssidName: string
        vlanGroupName: string
        wlanProfileName: string
    wirelessProfileName: string
- name: Delete by id
  cisco.catalystcenter.wireless_profiles:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: absent
    id: string
- name: Create
  cisco.catalystcenter.wireless_profiles:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: present
    additionalInterfaces:
      - string
    apZones:
      - apZoneName: string
        rfProfileName: string
        ssids:
          - string
    featureTemplates:
      - id: string
        ssids:
          - string
    id: string
    ssidDetails:
      - anchorGroupName: string
        dot11beProfileId: string
        enableFabric: true
        flexConnect:
          enableFlexConnect: true
          localToVlan: 0
        interfaceName: string
        policyProfileName: string
        ssidName: string
        vlanGroupName: string
        wlanProfileName: string
    wirelessProfileName: string
"""
RETURN = r"""
catalystcenter_response:
  description: A dictionary or list with the response returned by the Cisco Catalyst Center Python SDK
  returned: always
  type: dict
  sample: >
    {
      "response": {
        "taskId": "string",
        "url": "string"
      },
      "version": "string"
    }
"""
