#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: wireless_settings_pre_auth_acls
short_description: Resource module for Wireless Settings Pre Auth Acls
description:
  - Manage operations create, update and delete of the resource Wireless Settings Pre Auth Acls. - > This API allows users
    to create a Pre-Auth ACL design. To configure the created Pre-Auth ACL settings to an IOS-XE wireless supported device,.
    - > This API allows users to delete a Pre-Auth ACL by ID. This API will not remove the Pre-Auth ACL configured on a controller.
    To remove the provisioned Pre-Auth ACL settings from an IOS-XE wireless supported device,. - > This API allows users to
    update the details of an existing Pre-Auth ACL by ID. To configure the modified Pre- Auth ACL settings to an IOS-XE wireless
    supported device,.
version_added: '2.11.0'
extends_documentation_fragment:
  - cisco.catalystcenter.module
author: Bryan Vargas (@bvargasre)
options:
  aclListName:
    description: Pre-Auth ACL List Name.
    type: str
  aclName:
    description: Pre-Auth ACL Name.
    type: str
  id:
    description: Id path parameter. Pre-Auth ACL ID.
    type: str
  includeAutoGeneratedRules:
    description: If set to true, Predefined rules will be pushed, which include allowing DHCP, DNS, AAA, and other applicable
      ports and IPs that are created as part of the default pre-auth rule/ACE for the applicable SSID.
    type: bool
  ipAclRules:
    description: List of IPv4 or IPv6 ACL rules.
    elements: dict
    suboptions:
      destinationAddress:
        description: An IPv4 or IPv6 address.
        type: dict
      destinationPorts:
        description: Destination port. Required when protocol is TCP or UDP. Accepts a single number (e.g., 100) or a range
          with a hyphen and no whitespaces (e.g., 100-200). Valid values are between 0 and 65535.
        type: str
      destinationSubnetMaskOrPrefix:
        description: Destination subnet (IPv4) / Destination prefix (IPv6). Value should be in CIDR notation.
        type: int
      protocol:
        description: An IPv4 or IPv6 protocol.
        type: dict
      sourceAddress:
        description: An IPv4 or IPv6 address.
        type: dict
      sourcePorts:
        description: Source port. Required when protocol is TCP or UDP. Accepts a single number (e.g., 100) or a range with
          a hyphen and no whitespaces (e.g., 100-200). Valid values are between 0 and 65535.
        type: str
      sourceSubnetMaskOrPrefix:
        description: Source subnet (IPv4) / Source prefix (IPv6). Value should be in CIDR notation.
        type: int
    type: list
  ipv6AclEnabled:
    description: When set to true, only IPv6 ACL rules can be configured. When set to false, only IPv4 ACL rules can be configured.
      Default value of the attribute is false.
    type: bool
  walledGardenUrls:
    description: Walled Garden URLs. List of URLs that are allowed for access before a client device is fully authenticated
      to the network. Allowed special characters are hyphen(-), underscore(_), dot(.) and asterisk(*).
    elements: str
    type: list
requirements:
  - catalystcentersdk >= 3.1.6.0.2
  - python >= 3.12
seealso:
  - name: Cisco Catalyst Center documentation for Wireless CreatePreAuthACL
    description: Complete reference of the CreatePreAuthACL API.
    link: https://developer.cisco.com/docs/dna-center/#!create-pre-auth-acl
  - name: Cisco Catalyst Center documentation for Wireless DeletePreAuthACL
    description: Complete reference of the DeletePreAuthACL API.
    link: https://developer.cisco.com/docs/dna-center/#!delete-pre-auth-acl
  - name: Cisco Catalyst Center documentation for Wireless UpdatePreAuthACL
    description: Complete reference of the UpdatePreAuthACL API.
    link: https://developer.cisco.com/docs/dna-center/#!update-pre-auth-acl
notes:
  - SDK Method used are
    wireless.Wireless.create_pre_auth_acl,
    wireless.Wireless.delete_pre_auth_acl,
    wireless.Wireless.update_pre_auth_acl,
  - Paths used are
    post /dna/intent/api/v1/wirelessSettings/preAuthAcls,
    delete /dna/intent/api/v1/wirelessSettings/preAuthAcls/{id},
    put /dna/intent/api/v1/wirelessSettings/preAuthAcls/{id},
"""

EXAMPLES = r"""
---
- name: Delete by id
  cisco.catalystcenter.wireless_settings_pre_auth_acls:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: absent
    id: string
- name: Update by id
  cisco.catalystcenter.wireless_settings_pre_auth_acls:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: present
    aclListName: string
    aclName: string
    id: string
    includeAutoGeneratedRules: true
    ipAclRules:
      - destinationAddress: {}
        destinationPorts: string
        destinationSubnetMaskOrPrefix: 0
        protocol: {}
        sourceAddress: {}
        sourcePorts: string
        sourceSubnetMaskOrPrefix: 0
    ipv6AclEnabled: true
    walledGardenUrls:
      - string
- name: Create
  cisco.catalystcenter.wireless_settings_pre_auth_acls:
    catalystcenter_host: "{{catalystcenter_host}}"
    catalystcenter_username: "{{catalystcenter_username}}"
    catalystcenter_password: "{{catalystcenter_password}}"
    catalystcenter_verify: "{{catalystcenter_verify}}"
    catalystcenter_port: "{{catalystcenter_port}}"
    catalystcenter_version: "{{catalystcenter_version}}"
    catalystcenter_debug: "{{catalystcenter_debug}}"
    state: present
    aclListName: string
    aclName: string
    includeAutoGeneratedRules: true
    ipAclRules:
      - destinationAddress: {}
        destinationPorts: string
        destinationSubnetMaskOrPrefix: 0
        protocol: {}
        sourceAddress: {}
        sourcePorts: string
        sourceSubnetMaskOrPrefix: 0
    ipv6AclEnabled: true
    walledGardenUrls:
      - string
"""
RETURN = r"""
catalystcenter_response:
  description: A dictionary or list with the response returned by the Cisco Catalyst Center Python SDK
  returned: always
  type: dict
  sample: >
    {
      "response": {
        "taskId": "string",
        "url": "string"
      },
      "version": "string"
    }
"""
